from threading import Thread
from time import sleep
from django.shortcuts import render
from django.http import HttpResponse
from finalize.views import (
            AllIndiaGovernmentJobs,
            StatewiseGovtJobs,
            StatewiseTeachingJobs,
            StatewiseEngineeringJobs,
            RailwayJobs,
            PoliceJobs
        )


class FinishAll:
    def all_india_govt_jobs(request):
        try:
            res = AllIndiaGovernmentJobs.call_all_india_govt_jobs(request)
            return HttpResponse("success")
        except:
            return HttpResponse("error")


    def state_govt_jobs(request):
        t1 = Thread(target=StatewiseGovtJobs.call_andaman_govt_jobs,args=[request])
        t2 = Thread(target=StatewiseGovtJobs.call_odisha_govt_jobs,args=[request])
        t3 = Thread(target=StatewiseGovtJobs.call_andhra_govt_jobs,args=[request])
        t4 = Thread(target=StatewiseGovtJobs.call_arunachal_pradesh_govt_jobs,args=[request])
        t5 = Thread(target=StatewiseGovtJobs.call_assam_govt_jobs,args=[request])
        t6 = Thread(target=StatewiseGovtJobs.call_bihar_govt_jobs,args=[request])
        t7 = Thread(target=StatewiseGovtJobs.call_chandigarh_govt_jobs,args=[request])
        t8 = Thread(target=StatewiseGovtJobs.call_chhattisgarh_govt_jobs,args=[request])
        t9 = Thread(target=StatewiseGovtJobs.call_dadra_nagar_govt_jobs,args=[request])
        t10 = Thread(target=StatewiseGovtJobs.call_daman_diu_govt_jobs,args=[request])
        t11 = Thread(target=StatewiseGovtJobs.call_delhi_govt_jobs,args=[request])
        t12 = Thread(target=StatewiseGovtJobs.call_goa_govt_jobs,args=[request])
        t13 = Thread(target=StatewiseGovtJobs.call_gujurat_govt_jobs,args=[request])
        t14 = Thread(target=StatewiseGovtJobs.call_haryana_govt_jobs,args=[request])
        t15 = Thread(target=StatewiseGovtJobs.call_himachal_pradesh_govt_jobs,args=[request])
        t16 = Thread(target=StatewiseGovtJobs.call_jammu_kashmir_govt_jobs,args=[request])
        t17 = Thread(target=StatewiseGovtJobs.call_jharkhand_govt_jobs,args=[request])
        t18 = Thread(target=StatewiseGovtJobs.call_karnataka_govt_jobs,args=[request])
        t19 = Thread(target=StatewiseGovtJobs.call_kerala_govt_jobs,args=[request])
        t20 = Thread(target=StatewiseGovtJobs.call_lakshadweep_govt_jobs,args=[request])
        t21 = Thread(target=StatewiseGovtJobs.call_madhya_pradesh_govt_jobs,args=[request])
        t22 = Thread(target=StatewiseGovtJobs.call_maharashtra_govt_jobs,args=[request])
        t23 = Thread(target=StatewiseGovtJobs.call_manipur_govt_jobs,args=[request])
        t24 = Thread(target=StatewiseGovtJobs.call_meghalaya_govt_jobs,args=[request])
        t25 = Thread(target=StatewiseGovtJobs.call_mizoram_govt_jobs,args=[request])
        t26 = Thread(target=StatewiseGovtJobs.call_nagaland_govt_jobs,args=[request])
        t27 = Thread(target=StatewiseGovtJobs.call_puduchhery_govt_jobs,args=[request])
        t28 = Thread(target=StatewiseGovtJobs.call_punjab_govt_jobs,args=[request])
        t29 = Thread(target=StatewiseGovtJobs.call_rajastan_govt_jobs,args=[request])
        t30 = Thread(target=StatewiseGovtJobs.call_sikkim_govt_jobs,args=[request])
        t31 = Thread(target=StatewiseGovtJobs.call_tamil_nadu_govt_jobs,args=[request])
        t32 = Thread(target=StatewiseGovtJobs.call_telengana_govt_jobs,args=[request])
        t33 = Thread(target=StatewiseGovtJobs.call_tripura_govt_jobs,args=[request])
        t34 = Thread(target=StatewiseGovtJobs.call_uttarakhand_govt_jobs,args=[request])
        t35 = Thread(target=StatewiseGovtJobs.call_uttar_pradesh_govt_jobs,args=[request])
        t36 = Thread(target=StatewiseGovtJobs.call_west_bengal_govt_jobs,args=[request])

        t1.start()
        t2.start()
        t3.start()
        t4.start()
        t5.start()
        t6.start()
        t7.start()
        t8.start()
        t9.start()
        t10.start()
        t11.start()
        t12.start()
        t13.start()
        t14.start()
        t15.start()
        t16.start()
        t17.start()
        t18.start()
        t19.start()
        t20.start()
        t21.start()
        t22.start()
        t23.start()
        t24.start()
        t25.start()
        t26.start()
        t27.start()
        t28.start()
        t29.start()
        t30.start()
        t31.start()
        t32.start()
        t33.start()
        t34.start()
        t35.start()
        t36.start()


        t1.join()
        t2.join()
        t3.join()
        t4.join()
        t5.join()
        t6.join()
        t7.join()
        t8.join()
        t9.join()
        t10.join()
        t11.join()
        t12.join()
        t13.join()
        t14.join()
        t15.join()
        t16.join()
        t17.join()
        t18.join()
        t19.join()
        t20.join()
        t21.join()
        t22.join()
        t23.join()
        t24.join()
        t25.join()
        t26.join()
        t27.join()
        t28.join()
        t29.join()
        t30.join()
        t31.join()
        t32.join()
        t33.join()
        t34.join()
        t35.join()
        t36.join()



        return HttpResponse("success")
