from django.urls import path
from .views import *

urlpatterns = [
    #finalize all india
    path('call_all_india_govt_jobs/', AllIndiaGovernmentJobs.call_all_india_govt_jobs),
    #finalize statewise govt jobs
    path('call_andaman_govt_jobs/', StatewiseGovtJobs.call_andaman_govt_jobs),
    path('call_odisha_govt_jobs/', StatewiseGovtJobs.call_odisha_govt_jobs),
    path('call_andhra_govt_jobs/', StatewiseGovtJobs.call_andhra_govt_jobs),
    path('call_arunachal_pradesh_govt_jobs/', StatewiseGovtJobs.call_arunachal_pradesh_govt_jobs),
    path('call_assam_govt_jobs/', StatewiseGovtJobs.call_assam_govt_jobs),
    path('call_bihar_govt_jobs/', StatewiseGovtJobs.call_bihar_govt_jobs),
    path('call_chandigarh_govt_jobs/', StatewiseGovtJobs.call_chandigarh_govt_jobs),
    path('call_chhattishgarh_govt_jobs/', StatewiseGovtJobs.call_chhattisgarh_govt_jobs),
    path('call_dadra_nagar_govt_jobs/', StatewiseGovtJobs.call_dadra_nagar_govt_jobs),
    path('call_daman_diu_govt_jobs/', StatewiseGovtJobs.call_daman_diu_govt_jobs),
    path('call_delhi_govt_jobs/', StatewiseGovtJobs.call_delhi_govt_jobs),
    path('call_goa_govt_jobs/', StatewiseGovtJobs.call_goa_govt_jobs),
    path('call_gujurat_govt_jobs/', StatewiseGovtJobs.call_gujurat_govt_jobs),
    path('call_haryana_govt_jobs/', StatewiseGovtJobs.call_haryana_govt_jobs),
    path('call_himachal_pradesh_govt_jobs/', StatewiseGovtJobs.call_himachal_pradesh_govt_jobs),
    path('call_jammu_kashmir_govt_jobs/', StatewiseGovtJobs.call_jammu_kashmir_govt_jobs),
    path('call_jharkhand_govt_jobs/', StatewiseGovtJobs.call_jharkhand_govt_jobs),
    path('call_karnataka_govt_jobs/', StatewiseGovtJobs.call_karnataka_govt_jobs),
    path('call_kerala_govt_jobs/', StatewiseGovtJobs.call_kerala_govt_jobs),
    path('call_lakshadweep_govt_jobs/', StatewiseGovtJobs.call_lakshadweep_govt_jobs),
    path('call_madhya_pradesh_govt_jobs/', StatewiseGovtJobs.call_madhya_pradesh_govt_jobs),
    path('call_maharashtra_govt_jobs/', StatewiseGovtJobs.call_maharashtra_govt_jobs),
    path('call_manipur_govt_jobs/', StatewiseGovtJobs.call_manipur_govt_jobs),
    path('call_meghalaya_govt_jobs/', StatewiseGovtJobs.call_meghalaya_govt_jobs),
    path('call_mizoram_govt_jobs/', StatewiseGovtJobs.call_mizoram_govt_jobs),
    path('call_nagaland_govt_jobs/', StatewiseGovtJobs.call_nagaland_govt_jobs),
    path('call_puduchhery_govt_jobs/', StatewiseGovtJobs.call_puduchhery_govt_jobs),
    path('call_punjab_govt_jobs/', StatewiseGovtJobs.call_punjab_govt_jobs),
    path('call_rajastan_govt_jobs/', StatewiseGovtJobs.call_rajastan_govt_jobs),
    path('call_sikkim_govt_jobs/', StatewiseGovtJobs.call_sikkim_govt_jobs),
    path('call_tamil_nadu_govt_jobs/', StatewiseGovtJobs.call_tamil_nadu_govt_jobs),
    path('call_telengana_govt_jobs/', StatewiseGovtJobs.call_telengana_govt_jobs),
    path('call_tripura_govt_jobs/', StatewiseGovtJobs.call_tripura_govt_jobs),
    path('call_uttarakhand_govt_jobs/', StatewiseGovtJobs.call_uttarakhand_govt_jobs),
    path('call_uttar_pradesh_govt_jobs/', StatewiseGovtJobs.call_uttar_pradesh_govt_jobs),
    path('call_west_bengal_govt_jobs/', StatewiseGovtJobs.call_west_bengal_govt_jobs),
    #finalize teaching jobs:
    path('call_all_india_teaching_jobs/', StatewiseTeachingJobs.call_all_india_teaching_jobs),
    path('call_andaman_teaching_jobs/', StatewiseTeachingJobs.call_andaman_teaching_jobs),
    path('call_odisha_teaching_jobs/', StatewiseTeachingJobs.call_odisha_teaching_jobs),
    path('call_andhra_teaching_jobs/', StatewiseTeachingJobs.call_andhra_teaching_jobs),
    path('call_arunachal_pradesh_teaching_jobs/', StatewiseTeachingJobs.call_arunachal_pradesh_teaching_jobs),
    path('call_assam_teaching_jobs/', StatewiseTeachingJobs.call_assam_teaching_jobs),
    path('call_bihar_teaching_jobs/', StatewiseTeachingJobs.call_bihar_teaching_jobs),
    path('call_chandigarh_teaching_jobs/', StatewiseTeachingJobs.call_chandigarh_teaching_jobs),
    path('call_chhattisgarh_teaching_jobs/', StatewiseTeachingJobs.call_chhattisgarh_teaching_jobs),
    path('call_dadra_nagar_teaching_jobs/', StatewiseTeachingJobs.call_dadra_nagar_teaching_jobs),
    path('call_daman_diu_teaching_jobs/', StatewiseTeachingJobs.call_daman_diu_teaching_jobs),
    path('call_delhi_teaching_jobs/', StatewiseTeachingJobs.call_delhi_teaching_jobs),
    path('call_goa_teaching_jobs/', StatewiseTeachingJobs.call_goa_teaching_jobs),
    path('call_gujurat_teaching_jobs/', StatewiseTeachingJobs.call_gujurat_teaching_jobs),
    path('call_haryana_teaching_jobs/', StatewiseTeachingJobs.call_haryana_teaching_jobs),
    path('call_himachal_pradesh_teaching_jobs/', StatewiseTeachingJobs.call_himachal_pradesh_teaching_jobs),
    path('call_jammu_kashmir_teaching_jobs/', StatewiseTeachingJobs.call_jammu_kashmir_teaching_jobs),
    path('call_jharkhand_teaching_jobs/', StatewiseTeachingJobs.call_jharkhand_teaching_jobs),
    path('call_karnataka_teaching_jobs/', StatewiseTeachingJobs.call_karnataka_teaching_jobs),
    path('call_kerala_teaching_jobs/', StatewiseTeachingJobs.call_kerala_teaching_jobs),
    path('call_lakshadweep_teaching_jobs/', StatewiseTeachingJobs.call_lakshadweep_teaching_jobs),
    path('call_madhya_pradesh_teaching_jobs/', StatewiseTeachingJobs.call_madhya_pradesh_teaching_jobs),
    path('call_maharashtra_teaching_jobs/', StatewiseTeachingJobs.call_maharashtra_teaching_jobs),
    path('call_manipur_teaching_jobs/', StatewiseTeachingJobs.call_manipur_teaching_jobs),
    path('call_meghalaya_teaching_jobs/', StatewiseTeachingJobs.call_meghalaya_teaching_jobs),
    path('call_mizoram_teaching_jobs/', StatewiseTeachingJobs.call_mizoram_teaching_jobs),
    path('call_nagaland_teaching_jobs/', StatewiseTeachingJobs.call_nagaland_teaching_jobs),
    path('call_puduchhery_teaching_jobs/', StatewiseTeachingJobs.call_puduchhery_teaching_jobs),
    path('call_punjab_teaching_jobs/', StatewiseTeachingJobs.call_punjab_teaching_jobs),
    path('call_rajastan_teaching_jobs/', StatewiseTeachingJobs.call_rajastan_teaching_jobs),
    path('call_sikkim_teaching_jobs/', StatewiseTeachingJobs.call_sikkim_teaching_jobs),
    path('call_tamil_nadu_teaching_jobs/', StatewiseTeachingJobs.call_tamil_nadu_teaching_jobs),
    path('call_telengana_teaching_jobs/', StatewiseTeachingJobs.call_telengana_teaching_jobs),
    path('call_tripura_teaching_jobs/', StatewiseTeachingJobs.call_tripura_teaching_jobs),
    path('call_uttarakhand_teaching_jobs/', StatewiseTeachingJobs.call_uttarakhand_teaching_jobs),
    path('call_uttar_pradesh_teaching_jobs/', StatewiseTeachingJobs.call_uttar_pradesh_teaching_jobs),
    path('call_west_bengal_teaching_jobs/', StatewiseTeachingJobs.call_west_bengal_teaching_jobs),
    #finalize engineering jobs
    path('call_all_india_engg_jobs/', StatewiseEngineeringJobs.call_all_india_engg_jobs),
    path('call_all_india_fellow_engg_jobs/', StatewiseEngineeringJobs.call_all_india_fellow_engg_jobs),
    path('call_andaman_engg_jobs/', StatewiseEngineeringJobs.call_andaman_engg_jobs),
    path('call_odisha_engg_jobs/', StatewiseEngineeringJobs.call_odisha_engg_jobs),
    path('call_andhra_engg_jobs/', StatewiseEngineeringJobs.call_andhra_engg_jobs),
    path('call_arunachal_pradesh_engg_jobs/', StatewiseEngineeringJobs.call_arunachal_pradesh_engg_jobs),
    path('call_assam_engg_jobs/', StatewiseEngineeringJobs.call_assam_engg_jobs),
    path('call_bihar_engg_jobs/', StatewiseEngineeringJobs.call_bihar_engg_jobs),
    path('call_chandigarh_engg_jobs/', StatewiseEngineeringJobs.call_chandigarh_engg_jobs),
    path('call_chhattisgarh_engg_jobs/', StatewiseEngineeringJobs.call_chhattisgarh_engg_jobs),
    path('call_dadra_nagar_engg_jobs/', StatewiseEngineeringJobs.call_dadra_nagar_engg_jobs),
    path('call_daman_diu_engg_jobs/', StatewiseEngineeringJobs.call_daman_diu_engg_jobs),
    path('call_delhi_engg_jobs/', StatewiseEngineeringJobs.call_delhi_engg_jobs),
    path('call_goa_engg_jobs/', StatewiseEngineeringJobs.call_goa_engg_jobs),
    path('call_gujurat_engg_jobs/', StatewiseEngineeringJobs.call_gujurat_engg_jobs),
    path('call_haryana_engg_jobs/', StatewiseEngineeringJobs.call_haryana_engg_jobs),
    path('call_himachal_pradesh_engg_jobs/', StatewiseEngineeringJobs.call_himachal_pradesh_engg_jobs),
    path('call_jammu_kashmir_engg_jobs/', StatewiseEngineeringJobs.call_jammu_kashmir_engg_jobs),
    path('call_jharkhand_engg_jobs/', StatewiseEngineeringJobs.call_jharkhand_engg_jobs),
    path('call_karnataka_engg_jobs/', StatewiseEngineeringJobs.call_karnataka_engg_jobs),
    path('call_kerala_engg_jobs/', StatewiseEngineeringJobs.call_kerala_engg_jobs),
    path('call_lakshadweep_engg_jobs/', StatewiseEngineeringJobs.call_lakshadweep_engg_jobs),
    path('call_madhya_pradesh_engg_jobs/', StatewiseEngineeringJobs.call_madhya_pradesh_engg_jobs),
    path('call_maharashtra_engg_jobs/', StatewiseEngineeringJobs.call_maharashtra_engg_jobs),
    path('call_manipur_engg_jobs/', StatewiseEngineeringJobs.call_manipur_engg_jobs),
    path('call_meghalaya_engg_jobs/', StatewiseEngineeringJobs.call_meghalaya_engg_jobs),
    path('call_mizoram_engg_jobs/', StatewiseEngineeringJobs.call_mizoram_engg_jobs),
    path('call_nagaland_engg_jobs/', StatewiseEngineeringJobs.call_nagaland_engg_jobs),
    path('call_puduchhery_engg_jobs/', StatewiseEngineeringJobs.call_puduchhery_engg_jobs),
    path('call_punjab_engg_jobs/', StatewiseEngineeringJobs.call_punjab_engg_jobs),
    path('call_rajastan_engg_jobs/', StatewiseEngineeringJobs.call_rajastan_engg_jobs),
    path('call_sikkim_engg_jobs/', StatewiseEngineeringJobs.call_sikkim_engg_jobs),
    path('call_tamil_nadu_engg_jobs/', StatewiseEngineeringJobs.call_tamil_nadu_engg_jobs),
    path('call_telengana_engg_jobs/', StatewiseEngineeringJobs.call_telengana_engg_jobs),
    path('call_tripura_engg_jobs/', StatewiseEngineeringJobs.call_tripura_engg_jobs),
    path('call_uttarakhand_engg_jobs/', StatewiseEngineeringJobs.call_uttarakhand_engg_jobs),
    path('call_uttar_pradesh_engg_jobs/', StatewiseEngineeringJobs.call_uttar_pradesh_engg_jobs),
    path('call_west_bengal_engg_jobs/', StatewiseEngineeringJobs.call_west_bengal_engg_jobs),
    #finalize banking jobs
    path('call_all_bank_jobs/', BankingJobs.call_all_bank_jobs),
    path('call_other_financial_jobs/', BankingJobs.call_other_financial_jobs),
    #finalize railway jobs
    path('call_railway_jobs/', RailwayJobs.call_railway_jobs),
    #finalize police jobs
    path('call_police_defence_jobs/', PoliceJobs.call_police_defence_jobs),
    path('call_statewise_police_jobs/', PoliceJobs.call_statewise_police_jobs),

]
