# Generated by Django 2.1.1 on 2018-09-26 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndamanNicoborGovtJobs',
            fields=[
                ('andaman_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AndhraPradeshGovtJobs',
            fields=[
                ('andhra_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArunachalPradeshGovernmentjobs',
            fields=[
                ('arunachal_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssamGovtJobs',
            fields=[
                ('assam_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BiharGovtJobs',
            fields=[
                ('bihar_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChandigarhGovtJobs',
            fields=[
                ('chandigarh_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChhattisgarhGovtJobs',
            fields=[
                ('chhattisgarh_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OdishGovtJobs',
            fields=[
                ('odisha_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherAllIndiaJobs',
            fields=[
                ('other_all_india_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('requirement_board', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SscJobs',
            fields=[
                ('ssc_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpscJobs',
            fields=[
                ('upsc_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.CharField(max_length=60)),
                ('last_date', models.CharField(max_length=60)),
                ('post_name', models.CharField(max_length=255)),
                ('education', models.CharField(max_length=255)),
                ('more_info', models.TextField()),
                ('type', models.IntegerField()),
                ('job_id', models.IntegerField(blank=True, default=None, null=True)),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
