# Generated by Django 2.1.1 on 2018-09-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_policedefencejobs_railwayjobs_statewisepolicejobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoliceDefenceJobs',
        ),
    ]
