# Generated by Django 2.1.1 on 2018-09-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_policedefencejobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policedefencejobs',
            name='education',
        ),
        migrations.RemoveField(
            model_name='policedefencejobs',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='policedefencejobs',
            name='join_id',
        ),
        migrations.RemoveField(
            model_name='policedefencejobs',
            name='more_info',
        ),
        migrations.RemoveField(
            model_name='policedefencejobs',
            name='post_name',
        ),
        migrations.RemoveField(
            model_name='policedefencejobs',
            name='requirement_board',
        ),
        migrations.RemoveField(
            model_name='policedefencejobs',
            name='type',
        ),
    ]
