# Generated by Django 2.1.1 on 2018-09-27 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0009_auto_20180927_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RailwayJobs',
            new_name='RailwayJob',
        ),
    ]
