# Generated by Django 2.1.1 on 2018-09-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0010_auto_20180927_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allindiafellowenggjobs',
            old_name='all_india_id',
            new_name='all_india_fellow_id',
        ),
        migrations.RenameField(
            model_name='odishaenggjobs',
            old_name='puduchhery_id',
            new_name='odisha_id',
        ),
        migrations.RenameField(
            model_name='odishateachingjobs',
            old_name='puduchhery_id',
            new_name='odisha_id',
        ),
        migrations.RenameField(
            model_name='puduchheryenggjobs',
            old_name='punjab_id',
            new_name='puduchhery_id',
        ),
        migrations.RenameField(
            model_name='puduchheryteachingjobs',
            old_name='punjab_id',
            new_name='puduchhery_id',
        ),
    ]
