# Generated by Django 2.1.1 on 2018-10-26 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_auto_20180928_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RailwayJob',
            new_name='RailwayJobsModel',
        ),
    ]
