# Generated by Django 2.1.1 on 2018-12-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0013_auto_20181104_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allindiaenggjobs',
            old_name='all_india_id',
            new_name='id',
        ),
    ]
