# Generated by Django 2.1.1 on 2018-12-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0015_auto_20181206_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnggJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engg_jobs', models.TextField()),
            ],
        ),
    ]
