# Generated by Django 2.1.1 on 2018-09-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scrap', '0011_auto_20180928_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBankJobDetails',
            fields=[
                ('bankJobDetails_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('bankjobs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bankjobs_details', to='scrap.AllBankJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AllIndiaEnggJobDetails',
            fields=[
                ('all_india_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('all_india', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='all_india_details', to='scrap.AllIndiaEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AllIndiaFellowEnggJobDetails',
            fields=[
                ('all_india_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('all_india_fellow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='all_india_fellow_details', to='scrap.AllIndiaFellowEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AllIndiaTeachingJobDetails',
            fields=[
                ('all_india_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('all_india', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='all_india_details', to='scrap.AllIndiaTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AndamanNicoborEnggJobDetails',
            fields=[
                ('andaman_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('andaman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andaman_details', to='scrap.AndamanNicoborEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AndamanNicoborGovtJobDetails',
            fields=[
                ('andaman_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('andaman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andaman_details', to='scrap.AndamanNicoborGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AndamanNicoborTeachingJobDetails',
            fields=[
                ('andaman_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('andaman', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andaman_details', to='scrap.AndamanNicoborTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AndhraPradeshEnggJobDetails',
            fields=[
                ('andhra_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('andhra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andhra_details', to='scrap.AndhraPradeshEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AndhraPradeshGovtJobDetails',
            fields=[
                ('andhra_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('andhra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andhra_details', to='scrap.AndhraPradeshGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AndhraPradeshTeachingJobDetails',
            fields=[
                ('andhra_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('andhra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='andhra_details', to='scrap.AndhraPradeshTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ArunachalPradeshEnggJobDetails',
            fields=[
                ('arunachal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('arunachal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arunachal_details', to='scrap.ArunachalPradeshEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ArunachalPradeshGovernmentJobDetails',
            fields=[
                ('arunachal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('arunachal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arunachal_details', to='scrap.ArunachalPradeshGovernmentjobs')),
            ],
        ),
        migrations.CreateModel(
            name='ArunachalPradeshTeachingJobDetails',
            fields=[
                ('arunachal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('arunachal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arunachal_details', to='scrap.ArunachalPradeshTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AssamEnggJobDetails',
            fields=[
                ('assam_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('assam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assam_details', to='scrap.AssamEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AssamGovtJobDetails',
            fields=[
                ('assam_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('assam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assam_details', to='scrap.AssamGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='AssamTeachingJobDetails',
            fields=[
                ('assam_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('assam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assam_details', to='scrap.AssamTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='BiharEnggJobDetails',
            fields=[
                ('bihar_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('bihar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bihar_details', to='scrap.BiharEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='BiharGovtJobDetails',
            fields=[
                ('bihar_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('bihar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bihar_details', to='scrap.BiharGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='BiharTeachingJobDetails',
            fields=[
                ('bihar_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('bihar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bihar_details', to='scrap.BiharTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ChandigarhEnggJobDetails',
            fields=[
                ('chandigarh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('chandigarh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chandigarh_details', to='scrap.ChandigarhEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ChandigarhGovtJobDetails',
            fields=[
                ('chandigarh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('chandigarh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chandigarh_details', to='scrap.ChandigarhGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ChandigarhTeachingJobDetails',
            fields=[
                ('chandigarh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('chandigarh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chandigarh_details', to='scrap.ChandigarhTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ChhattisgarhEnggJobDetails',
            fields=[
                ('chhattisgarh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('chhattisgarh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chhattisgarh_details', to='scrap.ChhattisgarhEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ChhattisgarhGovtJobDetails',
            fields=[
                ('chhattisgarh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('chhattisgarh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chhattisgarh_details', to='scrap.ChhattisgarhGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ChhattisgarhTeachingJobDetails',
            fields=[
                ('chhattisgarh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('chhattisgarh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chhattisgarh_details', to='scrap.ChhattisgarhTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DadraNagarHaveliEnggJobDetails',
            fields=[
                ('dadra_nagar_haveli_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('dadra_nagar_haveli', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dadra_nagar_haveli_details', to='scrap.DadraNagarHaveliEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DadraNagarHaveliGovtJobDetails',
            fields=[
                ('dadra_nagar_haveli_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('dadra_nagar_haveli', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dadra_nagar_haveli_details', to='scrap.DadraNagarHaveliGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DadraNagarHaveliTeachingJobDetails',
            fields=[
                ('dadra_nagar_haveli_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('dadra_nagar_haveli', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dadra_nagar_haveli_details', to='scrap.DadraNagarHaveliTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DamanDiuEnggJobDetails',
            fields=[
                ('DamanDiuEnggJobDetails', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('daman_diu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daman_diu_details', to='scrap.DamanDiuEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DamanDiuGovtJobDetails',
            fields=[
                ('daman_diu_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('daman_diu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daman_diu_details', to='scrap.DamanDiuGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DamanDiuTeachingJobDetails',
            fields=[
                ('DamanDiuTeachingJobDetails', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('daman_diu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daman_diu_details', to='scrap.DamanDiuTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DelhiEnggJobDetails',
            fields=[
                ('delhi_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('delhi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delhi_details', to='scrap.DelhiEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DelhiGovtJobDetails',
            fields=[
                ('delhi_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('delhi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delhi_details', to='scrap.DelhiGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='DelhiTeachingJobDetails',
            fields=[
                ('delhi_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('delhi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delhi_details', to='scrap.DelhiTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='GoaEnggJobDetails',
            fields=[
                ('goa_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('goa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goa_details', to='scrap.GoaEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='GoaGovernmentJobDetails',
            fields=[
                ('goa_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('goa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goa_details', to='scrap.GoaGovernmentjobs')),
            ],
        ),
        migrations.CreateModel(
            name='GoaTeachingJobDetails',
            fields=[
                ('goa_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('goa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='goa_details', to='scrap.GoaTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='GujuratEnggJobDetails',
            fields=[
                ('gujurat_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('gujurat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gujurat_details', to='scrap.GujuratEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='GujuratGovtJobDetails',
            fields=[
                ('gujurat_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('gujurat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gujurat_details', to='scrap.GujuratGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='GujuratTeachingJobDetails',
            fields=[
                ('gujurat_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('gujurat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gujurat_details', to='scrap.GujuratTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='HaryanaEnggJobDetails',
            fields=[
                ('haryana_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('haryana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haryana_details', to='scrap.HaryanaEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='HaryanaGovtJobDetails',
            fields=[
                ('haryana_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('haryana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haryana_details', to='scrap.HaryanaGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='HaryanaTeachingJobDetails',
            fields=[
                ('haryana_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('haryana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='haryana_details', to='scrap.HaryanaTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='HimachalPradeshEnggJobDetails',
            fields=[
                ('himachal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('himachal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='himachal_details', to='scrap.HimachalPradeshEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='HimachalPradeshGovtJobDetails',
            fields=[
                ('himachal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('himachal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='himachal_details', to='scrap.HimachalPradeshGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='HimachalPradeshTeachingJobDetails',
            fields=[
                ('himachal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('himachal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='himachal_details', to='scrap.HimachalPradeshTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='JammuKashmirEnggJobDetails',
            fields=[
                ('jammu_kashmir_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('jammu_kashmir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jammu_kashmir_details', to='scrap.JammuKashmirEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='JammuKashmirGovtJobDetails',
            fields=[
                ('jammu_kashmir_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('jammu_kashmir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jammu_kashmir_details', to='scrap.JammuKashmirGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='JammuKashmirTeachingJobDetails',
            fields=[
                ('jammu_kashmir_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('jammu_kashmir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jammu_kashmir_details', to='scrap.JammuKashmirTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='JharkhandEnggJobDetails',
            fields=[
                ('jharkhand_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('jharkhand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jharkhand_details', to='scrap.JharkhandEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='JharkhandGovtJobDetails',
            fields=[
                ('jharkhand_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('jharkhand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jharkhand_details', to='scrap.JharkhandGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='JharkhandTeachingJobDetails',
            fields=[
                ('jharkhand_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('jharkhand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jharkhand_details', to='scrap.JharkhandTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='KarnatakaEnggJobDetails',
            fields=[
                ('karnataka_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('karnataka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karnataka_details', to='scrap.KarnatakaEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='KarnatakaGovtJobDetails',
            fields=[
                ('karnataka_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('karnataka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karnataka_details', to='scrap.KarnatakaGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='KarnatakaTeachingJobDetails',
            fields=[
                ('karnataka_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('karnataka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='karnataka_details', to='scrap.KarnatakaTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='KeralaEnggJobDetails',
            fields=[
                ('kerala_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('kerala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kerala_details', to='scrap.KeralaEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='KeralaGovtJobDetails',
            fields=[
                ('kerala_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('kerala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kerala_details', to='scrap.KeralaGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='KeralaTeachingJobDetails',
            fields=[
                ('kerala_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('kerala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kerala_details', to='scrap.KeralaTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='LakshadweepEnggJobDetails',
            fields=[
                ('lakshadweep_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('lakshadweep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lakshadweep_details', to='scrap.LakshadweepEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='LakshadweepGovernmentJobDetails',
            fields=[
                ('lakshadweep_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('lakshadweep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lakshadweep_details', to='scrap.LakshadweepGovernmentjobs')),
            ],
        ),
        migrations.CreateModel(
            name='LakshadweepTeachingJobDetails',
            fields=[
                ('lakshadweep_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('lakshadweep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lakshadweep_details', to='scrap.LakshadweepTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MadhyaPradeshEnggJobDetails',
            fields=[
                ('madhya_pradesh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('madhya_pradesh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='madhya_pradesh_details', to='scrap.MadhyaPradeshEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MadhyaPradeshGovtJobDetails',
            fields=[
                ('madhya_pradesh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('madhya_pradesh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='madhya_pradesh_details', to='scrap.MadhyaPradeshGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MadhyaPradeshTeachingJobDetails',
            fields=[
                ('madhya_pradesh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('madhya_pradesh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='madhya_pradesh_details', to='scrap.MadhyaPradeshTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MaharashtraEnggJobDetails',
            fields=[
                ('maharashtra_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('maharashtra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maharashtra_details', to='scrap.MaharashtraEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MaharashtraGovtJobDetails',
            fields=[
                ('maharashtra_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('maharashtra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maharashtra_details', to='scrap.MaharashtraGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MaharashtraTeachingJobDetails',
            fields=[
                ('maharashtra_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('maharashtra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maharashtra_details', to='scrap.MaharashtraTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ManipurEnggJobDetails',
            fields=[
                ('manipur_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('manipur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manipur_details', to='scrap.ManipurEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ManipurGovtJobDetails',
            fields=[
                ('manipur_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('manipur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manipur_details', to='scrap.ManipurGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='ManipurTeachingJobDetails',
            fields=[
                ('manipur_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('manipur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manipur_details', to='scrap.ManipurTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MeghalayaEnggJobDetails',
            fields=[
                ('meghalaya_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('meghalaya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meghalaya_details', to='scrap.MeghalayaEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MeghalayaGovtJobDetails',
            fields=[
                ('meghalaya_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('meghalaya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meghalaya_details', to='scrap.MeghalayaGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MeghalayaTeachingJobDetails',
            fields=[
                ('meghalaya_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('meghalaya', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meghalaya_details', to='scrap.MeghalayaTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MizoramEnggJobDetails',
            fields=[
                ('mizoram_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('mizoram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mizoram_details', to='scrap.MizoramEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MizoramGovtJobDetails',
            fields=[
                ('mizoram_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('mizoram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mizoram_details', to='scrap.MizoramGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='MizoramTeachingJobDetails',
            fields=[
                ('mizoram_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('mizoram', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mizoram_details', to='scrap.MizoramTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='NagalandEnggJobDetails',
            fields=[
                ('nagaland_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('nagaland', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nagaland_details', to='scrap.NagalandEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='NagalandGovtJobDetails',
            fields=[
                ('nagaland_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('nagaland', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nagaland_details', to='scrap.NagalandGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='NagalandTeachingJobDetails',
            fields=[
                ('nagaland_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('nagaland', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nagaland_details', to='scrap.NagalandTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='OdishaEnggJobDetails',
            fields=[
                ('odisha_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('odisha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odisha_details', to='scrap.OdishaEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='OdishaGovtJobDetails',
            fields=[
                ('odisha_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('odisha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odisha_details', to='scrap.OdishaGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='OdishaTeachingJobDetails',
            fields=[
                ('odisha_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('odisha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odisha_details', to='scrap.OdishaTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='OtherAllIndiaJobDetails',
            fields=[
                ('other_all_india_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('other_all_india', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_all_india_details', to='scrap.OtherAllIndiaJobs')),
            ],
        ),
        migrations.CreateModel(
            name='OtherFinancialJobDetails',
            fields=[
                ('financialJobDetails_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('financialjobs', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='other_financialjobs_details', to='scrap.OtherFinancialJobs')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceAndDefenceJobDetails',
            fields=[
                ('police_defence_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('police_defence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='police_defence_details', to='scrap.PoliceAndDefenceJobs')),
            ],
        ),
        migrations.CreateModel(
            name='PuduchheryEnggJobDetails',
            fields=[
                ('puduchhery_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('puduchhery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puduchhery_details', to='scrap.PuduchheryEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='PuduchheryGovtJobDetails',
            fields=[
                ('puduchhery_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('puduchhery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puduchhery_details', to='scrap.PuduchheryGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='PuduchheryTeachingJobDetails',
            fields=[
                ('punjab_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('puduchhery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puduchhery_details', to='scrap.PuduchheryTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='PunjabEnggJobDetails',
            fields=[
                ('punjab_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('punjab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punjab_details', to='scrap.PunjabEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='PunjabGovernmentJobDetails',
            fields=[
                ('punjab_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('punjab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punjab_details', to='scrap.PunjabGovernmentjobs')),
            ],
        ),
        migrations.CreateModel(
            name='PunjabTeachingJobDetails',
            fields=[
                ('punjab_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('punjab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='punjab_details', to='scrap.PunjabTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='RailwayJobDetails',
            fields=[
                ('railway_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('railway', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='railway_details', to='scrap.RailwayJob')),
            ],
        ),
        migrations.CreateModel(
            name='RajasthanEnggJobDetails',
            fields=[
                ('rajasthan_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('rajasthan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rajasthan_details', to='scrap.RajasthanEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='RajasthanGovtJobDetails',
            fields=[
                ('rajasthan_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('rajasthan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rajasthan_details', to='scrap.RajasthanGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='RajasthanTeachingJobDetails',
            fields=[
                ('rajasthan_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('rajasthan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rajasthan_details', to='scrap.RajasthanTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='SikkimEnggJobDetails',
            fields=[
                ('sikkim_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('sikkim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sikkim_details', to='scrap.SikkimEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='SikkimGovtJobDetails',
            fields=[
                ('sikkim_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('sikkim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sikkim_details', to='scrap.SikkimGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='SikkimTeachingJobDetails',
            fields=[
                ('sikkim_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('sikkim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sikkim_details', to='scrap.SikkimTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='SscJobDetails',
            fields=[
                ('ssc_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('ssc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssc_details', to='scrap.SscJobs')),
            ],
        ),
        migrations.CreateModel(
            name='StatewisePoliceJobDetails',
            fields=[
                ('statewise_police_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('statewise_police', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statewise_police_details', to='scrap.StatewisePoliceJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TamilGovtJobDetails',
            fields=[
                ('tamil_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('tamil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tamil_details', to='scrap.TamilGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TamilNaduEnggJobDetails',
            fields=[
                ('tamil_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('tamil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tamil_details', to='scrap.TamilNaduEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TamilNaduTeachingJobDetails',
            fields=[
                ('tamil_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('tamil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tamil_details', to='scrap.TamilNaduTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TelanganaEnggJobDetails',
            fields=[
                ('telangana_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('telangana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telangana_details', to='scrap.TelanganaEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TelanganaGovtJobDetails',
            fields=[
                ('telangana_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('telangana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telangana_details', to='scrap.TelanganaGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TelanganaTeachingJobDetails',
            fields=[
                ('telangana_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('telangana', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telangana_details', to='scrap.TelanganaTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TripuraEnggJobDetails',
            fields=[
                ('tripura_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('tripura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tripura_details', to='scrap.TripuraEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TripuraGovtJobDetails',
            fields=[
                ('tripura_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('tripura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tripura_details', to='scrap.TripuraGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='TripuraTeachingJobDetails',
            fields=[
                ('tripura_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('tripura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tripura_details', to='scrap.TripuraTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='UpscJobDetails',
            fields=[
                ('upsc_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('upsc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upsc_details', to='scrap.UpscJobs')),
            ],
        ),
        migrations.CreateModel(
            name='UttarakhandEnggJobDetails',
            fields=[
                ('uttarakhand_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('uttarakhand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uttarakhand_details', to='scrap.UttarakhandEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='UttarakhandGovtJobDetails',
            fields=[
                ('uttarakhand_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('uttarakhand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uttarakhand_details', to='scrap.UttarakhandGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='UttarakhandTeachingJobDetails',
            fields=[
                ('uttarakhand_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('uttarakhand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uttarakhand_details', to='scrap.UttarakhandTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='UttarPradeshEnggJobDetails',
            fields=[
                ('uttar_pradesh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('uttar_pradesh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uttar_pradesh_details', to='scrap.UttarPradeshEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='UttarPradeshGovtJobDetails',
            fields=[
                ('uttar_pradesh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('uttar_pradesh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uttar_pradesh_details', to='scrap.UttarPradeshGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='UttarPradeshTeachingJobDetails',
            fields=[
                ('uttar_pradesh_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('uttar_pradesh', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uttar_pradesh_details', to='scrap.UttarPradeshTeachingJobs')),
            ],
        ),
        migrations.CreateModel(
            name='WestBengalEnggJobDetails',
            fields=[
                ('west_bengal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('west_bengal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='west_bengal_details', to='scrap.WestBengalEnggJobs')),
            ],
        ),
        migrations.CreateModel(
            name='WestBengalGovtJobDetails',
            fields=[
                ('west_bengal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('west_bengal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='west_bengal_details', to='scrap.WestBengalGovtJobs')),
            ],
        ),
        migrations.CreateModel(
            name='WestBengalTeachingJobDetails',
            fields=[
                ('west_bengal_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('more_info', models.TextField()),
                ('join_id', models.IntegerField(blank=True, default=None, null=True)),
                ('west_bengal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='west_bengal_details', to='scrap.WestBengalTeachingJobs')),
            ],
        ),
    ]
