# Generated by Django 2.1.1 on 2018-10-03 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andhrapradeshgovtjobdetails',
            name='andhra',
        ),
    ]
