# Generated by Django 2.1.1 on 2018-10-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_remove_andhrapradeshgovtjobdetails_andhra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andamannicoborgovtjobdetails',
            name='andaman',
        ),
        migrations.RemoveField(
            model_name='odishagovtjobdetails',
            name='odisha',
        ),
    ]
