# Generated by Django 2.1.1 on 2018-10-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_auto_20181005_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allbankjobdetails',
            name='bankjobs',
        ),
        migrations.RemoveField(
            model_name='otherfinancialjobdetails',
            name='financialjobs',
        ),
    ]
