# Generated by Django 2.1.1 on 2018-12-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0007_remove_otherallindiajobdetails_other_all_india'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allindiaenggjobdetails',
            old_name='all_india_details_id',
            new_name='id',
        ),
    ]
